---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: lupanar
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: lupanar
      owner: lupanar
      secret:
        name: db-secret
