---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lupanar
  name: bot
  labels:
    app.kubernetes.io/name: bot
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bot
        service.opentelemetry.io/name: lupanar.bot
    spec:
      volumes:
        - name: atlas
          secret:
            secretName: atlas
      initContainers:
        - name: migrate
          image: ghcr.io/ernado/lupanarbot/migrate:main
          volumeMounts:
            - mountPath: "/root/.config/"
              name: atlas
              readOnly: true
          args:
            - --config
            - file://root/.config/atlas.hcl
            - --env
            - prod
            - migrate
            - apply
          resources:
            requests:
              cpu: 100m
              memory: 64M
            limits:
              cpu: 500m
              memory: 128M
      containers:
        - name: bot
          image: ghcr.io/ernado/lupanarbot:main
          resources:
            requests:
              cpu: 100m
              memory: 64M
            limits:
              cpu: 500m
              memory: 256M
          env:
            - name: GOMEMLIMIT
              value: "256MiB"
            - name: GOMAXPROCS
              value: "1"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_METRICS_EXPORTER
              value: "prometheus"
            - name: OTEL_EXPORTER_PROMETHEUS_PORT
              value: "8090"
            - name: OTEL_EXPORTER_PROMETHEUS_HOST
              value: "0.0.0.0"
            - name: PPROF_ADDR
              value: "0.0.0.0:8090"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=lupanar.bot"
            - name: OTEL_LOG_LEVEL
              value: "DEBUG"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
            - name: HOME
              value: /cache
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: BOT_TOKEN
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: APP_ID
            - name: APP_HASH
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: APP_HASH
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: DATABASE_URL
