// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TelegramChannelsColumns holds the columns for the "telegram_channels" table.
	TelegramChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "access_hash", Type: field.TypeInt64},
		{Name: "title", Type: field.TypeString},
		{Name: "active", Type: field.TypeBool},
	}
	// TelegramChannelsTable holds the schema information for the "telegram_channels" table.
	TelegramChannelsTable = &schema.Table{
		Name:       "telegram_channels",
		Columns:    TelegramChannelsColumns,
		PrimaryKey: []*schema.Column{TelegramChannelsColumns[0]},
	}
	// TelegramSessionsColumns holds the columns for the "telegram_sessions" table.
	TelegramSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "data", Type: field.TypeBytes},
	}
	// TelegramSessionsTable holds the schema information for the "telegram_sessions" table.
	TelegramSessionsTable = &schema.Table{
		Name:       "telegram_sessions",
		Columns:    TelegramSessionsColumns,
		PrimaryKey: []*schema.Column{TelegramSessionsColumns[0]},
	}
	// TriesColumns holds the columns for the "tries" table.
	TriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"Extremism", "Constitution", "CriminalCode"}},
	}
	// TriesTable holds the schema information for the "tries" table.
	TriesTable = &schema.Table{
		Name:       "tries",
		Columns:    TriesColumns,
		PrimaryKey: []*schema.Column{TriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "try_id_type",
				Unique:  true,
				Columns: []*schema.Column{TriesColumns[0], TriesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TelegramChannelsTable,
		TelegramSessionsTable,
		TriesTable,
	}
)

func init() {
}
