// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ernado/lupanarbot/internal/ent/lasttry"
	"github.com/ernado/lupanarbot/internal/ent/predicate"
)

// LastTryUpdate is the builder for updating LastTry entities.
type LastTryUpdate struct {
	config
	hooks    []Hook
	mutation *LastTryMutation
}

// Where appends a list predicates to the LastTryUpdate builder.
func (ltu *LastTryUpdate) Where(ps ...predicate.LastTry) *LastTryUpdate {
	ltu.mutation.Where(ps...)
	return ltu
}

// SetTry sets the "try" field.
func (ltu *LastTryUpdate) SetTry(t time.Time) *LastTryUpdate {
	ltu.mutation.SetTry(t)
	return ltu
}

// SetNillableTry sets the "try" field if the given value is not nil.
func (ltu *LastTryUpdate) SetNillableTry(t *time.Time) *LastTryUpdate {
	if t != nil {
		ltu.SetTry(*t)
	}
	return ltu
}

// Mutation returns the LastTryMutation object of the builder.
func (ltu *LastTryUpdate) Mutation() *LastTryMutation {
	return ltu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ltu *LastTryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ltu.sqlSave, ltu.mutation, ltu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ltu *LastTryUpdate) SaveX(ctx context.Context) int {
	affected, err := ltu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ltu *LastTryUpdate) Exec(ctx context.Context) error {
	_, err := ltu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ltu *LastTryUpdate) ExecX(ctx context.Context) {
	if err := ltu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ltu *LastTryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(lasttry.Table, lasttry.Columns, sqlgraph.NewFieldSpec(lasttry.FieldID, field.TypeInt64))
	if ps := ltu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ltu.mutation.Try(); ok {
		_spec.SetField(lasttry.FieldTry, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ltu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lasttry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ltu.mutation.done = true
	return n, nil
}

// LastTryUpdateOne is the builder for updating a single LastTry entity.
type LastTryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LastTryMutation
}

// SetTry sets the "try" field.
func (ltuo *LastTryUpdateOne) SetTry(t time.Time) *LastTryUpdateOne {
	ltuo.mutation.SetTry(t)
	return ltuo
}

// SetNillableTry sets the "try" field if the given value is not nil.
func (ltuo *LastTryUpdateOne) SetNillableTry(t *time.Time) *LastTryUpdateOne {
	if t != nil {
		ltuo.SetTry(*t)
	}
	return ltuo
}

// Mutation returns the LastTryMutation object of the builder.
func (ltuo *LastTryUpdateOne) Mutation() *LastTryMutation {
	return ltuo.mutation
}

// Where appends a list predicates to the LastTryUpdate builder.
func (ltuo *LastTryUpdateOne) Where(ps ...predicate.LastTry) *LastTryUpdateOne {
	ltuo.mutation.Where(ps...)
	return ltuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ltuo *LastTryUpdateOne) Select(field string, fields ...string) *LastTryUpdateOne {
	ltuo.fields = append([]string{field}, fields...)
	return ltuo
}

// Save executes the query and returns the updated LastTry entity.
func (ltuo *LastTryUpdateOne) Save(ctx context.Context) (*LastTry, error) {
	return withHooks(ctx, ltuo.sqlSave, ltuo.mutation, ltuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ltuo *LastTryUpdateOne) SaveX(ctx context.Context) *LastTry {
	node, err := ltuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ltuo *LastTryUpdateOne) Exec(ctx context.Context) error {
	_, err := ltuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ltuo *LastTryUpdateOne) ExecX(ctx context.Context) {
	if err := ltuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ltuo *LastTryUpdateOne) sqlSave(ctx context.Context) (_node *LastTry, err error) {
	_spec := sqlgraph.NewUpdateSpec(lasttry.Table, lasttry.Columns, sqlgraph.NewFieldSpec(lasttry.FieldID, field.TypeInt64))
	id, ok := ltuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LastTry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ltuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lasttry.FieldID)
		for _, f := range fields {
			if !lasttry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lasttry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ltuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ltuo.mutation.Try(); ok {
		_spec.SetField(lasttry.FieldTry, field.TypeTime, value)
	}
	_node = &LastTry{config: ltuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ltuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lasttry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ltuo.mutation.done = true
	return _node, nil
}
