// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ernado/lupanarbot/internal/ent/lasttry"
	"github.com/ernado/lupanarbot/internal/ent/predicate"
)

// LastTryQuery is the builder for querying LastTry entities.
type LastTryQuery struct {
	config
	ctx        *QueryContext
	order      []lasttry.OrderOption
	inters     []Interceptor
	predicates []predicate.LastTry
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LastTryQuery builder.
func (ltq *LastTryQuery) Where(ps ...predicate.LastTry) *LastTryQuery {
	ltq.predicates = append(ltq.predicates, ps...)
	return ltq
}

// Limit the number of records to be returned by this query.
func (ltq *LastTryQuery) Limit(limit int) *LastTryQuery {
	ltq.ctx.Limit = &limit
	return ltq
}

// Offset to start from.
func (ltq *LastTryQuery) Offset(offset int) *LastTryQuery {
	ltq.ctx.Offset = &offset
	return ltq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ltq *LastTryQuery) Unique(unique bool) *LastTryQuery {
	ltq.ctx.Unique = &unique
	return ltq
}

// Order specifies how the records should be ordered.
func (ltq *LastTryQuery) Order(o ...lasttry.OrderOption) *LastTryQuery {
	ltq.order = append(ltq.order, o...)
	return ltq
}

// First returns the first LastTry entity from the query.
// Returns a *NotFoundError when no LastTry was found.
func (ltq *LastTryQuery) First(ctx context.Context) (*LastTry, error) {
	nodes, err := ltq.Limit(1).All(setContextOp(ctx, ltq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lasttry.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ltq *LastTryQuery) FirstX(ctx context.Context) *LastTry {
	node, err := ltq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LastTry ID from the query.
// Returns a *NotFoundError when no LastTry ID was found.
func (ltq *LastTryQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ltq.Limit(1).IDs(setContextOp(ctx, ltq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lasttry.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ltq *LastTryQuery) FirstIDX(ctx context.Context) int64 {
	id, err := ltq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LastTry entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LastTry entity is found.
// Returns a *NotFoundError when no LastTry entities are found.
func (ltq *LastTryQuery) Only(ctx context.Context) (*LastTry, error) {
	nodes, err := ltq.Limit(2).All(setContextOp(ctx, ltq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lasttry.Label}
	default:
		return nil, &NotSingularError{lasttry.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ltq *LastTryQuery) OnlyX(ctx context.Context) *LastTry {
	node, err := ltq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LastTry ID in the query.
// Returns a *NotSingularError when more than one LastTry ID is found.
// Returns a *NotFoundError when no entities are found.
func (ltq *LastTryQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ltq.Limit(2).IDs(setContextOp(ctx, ltq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lasttry.Label}
	default:
		err = &NotSingularError{lasttry.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ltq *LastTryQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := ltq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LastTries.
func (ltq *LastTryQuery) All(ctx context.Context) ([]*LastTry, error) {
	ctx = setContextOp(ctx, ltq.ctx, ent.OpQueryAll)
	if err := ltq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LastTry, *LastTryQuery]()
	return withInterceptors[[]*LastTry](ctx, ltq, qr, ltq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ltq *LastTryQuery) AllX(ctx context.Context) []*LastTry {
	nodes, err := ltq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LastTry IDs.
func (ltq *LastTryQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if ltq.ctx.Unique == nil && ltq.path != nil {
		ltq.Unique(true)
	}
	ctx = setContextOp(ctx, ltq.ctx, ent.OpQueryIDs)
	if err = ltq.Select(lasttry.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ltq *LastTryQuery) IDsX(ctx context.Context) []int64 {
	ids, err := ltq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ltq *LastTryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ltq.ctx, ent.OpQueryCount)
	if err := ltq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ltq, querierCount[*LastTryQuery](), ltq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ltq *LastTryQuery) CountX(ctx context.Context) int {
	count, err := ltq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ltq *LastTryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ltq.ctx, ent.OpQueryExist)
	switch _, err := ltq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ltq *LastTryQuery) ExistX(ctx context.Context) bool {
	exist, err := ltq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LastTryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ltq *LastTryQuery) Clone() *LastTryQuery {
	if ltq == nil {
		return nil
	}
	return &LastTryQuery{
		config:     ltq.config,
		ctx:        ltq.ctx.Clone(),
		order:      append([]lasttry.OrderOption{}, ltq.order...),
		inters:     append([]Interceptor{}, ltq.inters...),
		predicates: append([]predicate.LastTry{}, ltq.predicates...),
		// clone intermediate query.
		sql:  ltq.sql.Clone(),
		path: ltq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Try time.Time `json:"try,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LastTry.Query().
//		GroupBy(lasttry.FieldTry).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ltq *LastTryQuery) GroupBy(field string, fields ...string) *LastTryGroupBy {
	ltq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LastTryGroupBy{build: ltq}
	grbuild.flds = &ltq.ctx.Fields
	grbuild.label = lasttry.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Try time.Time `json:"try,omitempty"`
//	}
//
//	client.LastTry.Query().
//		Select(lasttry.FieldTry).
//		Scan(ctx, &v)
func (ltq *LastTryQuery) Select(fields ...string) *LastTrySelect {
	ltq.ctx.Fields = append(ltq.ctx.Fields, fields...)
	sbuild := &LastTrySelect{LastTryQuery: ltq}
	sbuild.label = lasttry.Label
	sbuild.flds, sbuild.scan = &ltq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LastTrySelect configured with the given aggregations.
func (ltq *LastTryQuery) Aggregate(fns ...AggregateFunc) *LastTrySelect {
	return ltq.Select().Aggregate(fns...)
}

func (ltq *LastTryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ltq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ltq); err != nil {
				return err
			}
		}
	}
	for _, f := range ltq.ctx.Fields {
		if !lasttry.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ltq.path != nil {
		prev, err := ltq.path(ctx)
		if err != nil {
			return err
		}
		ltq.sql = prev
	}
	return nil
}

func (ltq *LastTryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LastTry, error) {
	var (
		nodes = []*LastTry{}
		_spec = ltq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LastTry).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LastTry{config: ltq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ltq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ltq *LastTryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ltq.querySpec()
	_spec.Node.Columns = ltq.ctx.Fields
	if len(ltq.ctx.Fields) > 0 {
		_spec.Unique = ltq.ctx.Unique != nil && *ltq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ltq.driver, _spec)
}

func (ltq *LastTryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(lasttry.Table, lasttry.Columns, sqlgraph.NewFieldSpec(lasttry.FieldID, field.TypeInt64))
	_spec.From = ltq.sql
	if unique := ltq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ltq.path != nil {
		_spec.Unique = true
	}
	if fields := ltq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lasttry.FieldID)
		for i := range fields {
			if fields[i] != lasttry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ltq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ltq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ltq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ltq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ltq *LastTryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ltq.driver.Dialect())
	t1 := builder.Table(lasttry.Table)
	columns := ltq.ctx.Fields
	if len(columns) == 0 {
		columns = lasttry.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ltq.sql != nil {
		selector = ltq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ltq.ctx.Unique != nil && *ltq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ltq.predicates {
		p(selector)
	}
	for _, p := range ltq.order {
		p(selector)
	}
	if offset := ltq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ltq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LastTryGroupBy is the group-by builder for LastTry entities.
type LastTryGroupBy struct {
	selector
	build *LastTryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ltgb *LastTryGroupBy) Aggregate(fns ...AggregateFunc) *LastTryGroupBy {
	ltgb.fns = append(ltgb.fns, fns...)
	return ltgb
}

// Scan applies the selector query and scans the result into the given value.
func (ltgb *LastTryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ltgb.build.ctx, ent.OpQueryGroupBy)
	if err := ltgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LastTryQuery, *LastTryGroupBy](ctx, ltgb.build, ltgb, ltgb.build.inters, v)
}

func (ltgb *LastTryGroupBy) sqlScan(ctx context.Context, root *LastTryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ltgb.fns))
	for _, fn := range ltgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ltgb.flds)+len(ltgb.fns))
		for _, f := range *ltgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ltgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ltgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LastTrySelect is the builder for selecting fields of LastTry entities.
type LastTrySelect struct {
	*LastTryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lts *LastTrySelect) Aggregate(fns ...AggregateFunc) *LastTrySelect {
	lts.fns = append(lts.fns, fns...)
	return lts
}

// Scan applies the selector query and scans the result into the given value.
func (lts *LastTrySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lts.ctx, ent.OpQuerySelect)
	if err := lts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LastTryQuery, *LastTrySelect](ctx, lts.LastTryQuery, lts, lts.inters, v)
}

func (lts *LastTrySelect) sqlScan(ctx context.Context, root *LastTryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lts.fns))
	for _, fn := range lts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
