// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cydev/cgbot/internal/ent/predicate"
	"github.com/cydev/cgbot/internal/ent/telegramchannel"
)

// TelegramChannelQuery is the builder for querying TelegramChannel entities.
type TelegramChannelQuery struct {
	config
	ctx        *QueryContext
	order      []telegramchannel.OrderOption
	inters     []Interceptor
	predicates []predicate.TelegramChannel
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TelegramChannelQuery builder.
func (tcq *TelegramChannelQuery) Where(ps ...predicate.TelegramChannel) *TelegramChannelQuery {
	tcq.predicates = append(tcq.predicates, ps...)
	return tcq
}

// Limit the number of records to be returned by this query.
func (tcq *TelegramChannelQuery) Limit(limit int) *TelegramChannelQuery {
	tcq.ctx.Limit = &limit
	return tcq
}

// Offset to start from.
func (tcq *TelegramChannelQuery) Offset(offset int) *TelegramChannelQuery {
	tcq.ctx.Offset = &offset
	return tcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tcq *TelegramChannelQuery) Unique(unique bool) *TelegramChannelQuery {
	tcq.ctx.Unique = &unique
	return tcq
}

// Order specifies how the records should be ordered.
func (tcq *TelegramChannelQuery) Order(o ...telegramchannel.OrderOption) *TelegramChannelQuery {
	tcq.order = append(tcq.order, o...)
	return tcq
}

// First returns the first TelegramChannel entity from the query.
// Returns a *NotFoundError when no TelegramChannel was found.
func (tcq *TelegramChannelQuery) First(ctx context.Context) (*TelegramChannel, error) {
	nodes, err := tcq.Limit(1).All(setContextOp(ctx, tcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{telegramchannel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tcq *TelegramChannelQuery) FirstX(ctx context.Context) *TelegramChannel {
	node, err := tcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TelegramChannel ID from the query.
// Returns a *NotFoundError when no TelegramChannel ID was found.
func (tcq *TelegramChannelQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = tcq.Limit(1).IDs(setContextOp(ctx, tcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{telegramchannel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tcq *TelegramChannelQuery) FirstIDX(ctx context.Context) int64 {
	id, err := tcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TelegramChannel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TelegramChannel entity is found.
// Returns a *NotFoundError when no TelegramChannel entities are found.
func (tcq *TelegramChannelQuery) Only(ctx context.Context) (*TelegramChannel, error) {
	nodes, err := tcq.Limit(2).All(setContextOp(ctx, tcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{telegramchannel.Label}
	default:
		return nil, &NotSingularError{telegramchannel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tcq *TelegramChannelQuery) OnlyX(ctx context.Context) *TelegramChannel {
	node, err := tcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TelegramChannel ID in the query.
// Returns a *NotSingularError when more than one TelegramChannel ID is found.
// Returns a *NotFoundError when no entities are found.
func (tcq *TelegramChannelQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = tcq.Limit(2).IDs(setContextOp(ctx, tcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{telegramchannel.Label}
	default:
		err = &NotSingularError{telegramchannel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tcq *TelegramChannelQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := tcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TelegramChannels.
func (tcq *TelegramChannelQuery) All(ctx context.Context) ([]*TelegramChannel, error) {
	ctx = setContextOp(ctx, tcq.ctx, ent.OpQueryAll)
	if err := tcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TelegramChannel, *TelegramChannelQuery]()
	return withInterceptors[[]*TelegramChannel](ctx, tcq, qr, tcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tcq *TelegramChannelQuery) AllX(ctx context.Context) []*TelegramChannel {
	nodes, err := tcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TelegramChannel IDs.
func (tcq *TelegramChannelQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if tcq.ctx.Unique == nil && tcq.path != nil {
		tcq.Unique(true)
	}
	ctx = setContextOp(ctx, tcq.ctx, ent.OpQueryIDs)
	if err = tcq.Select(telegramchannel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tcq *TelegramChannelQuery) IDsX(ctx context.Context) []int64 {
	ids, err := tcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tcq *TelegramChannelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tcq.ctx, ent.OpQueryCount)
	if err := tcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tcq, querierCount[*TelegramChannelQuery](), tcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tcq *TelegramChannelQuery) CountX(ctx context.Context) int {
	count, err := tcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tcq *TelegramChannelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tcq.ctx, ent.OpQueryExist)
	switch _, err := tcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tcq *TelegramChannelQuery) ExistX(ctx context.Context) bool {
	exist, err := tcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TelegramChannelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tcq *TelegramChannelQuery) Clone() *TelegramChannelQuery {
	if tcq == nil {
		return nil
	}
	return &TelegramChannelQuery{
		config:     tcq.config,
		ctx:        tcq.ctx.Clone(),
		order:      append([]telegramchannel.OrderOption{}, tcq.order...),
		inters:     append([]Interceptor{}, tcq.inters...),
		predicates: append([]predicate.TelegramChannel{}, tcq.predicates...),
		// clone intermediate query.
		sql:  tcq.sql.Clone(),
		path: tcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AccessHash int64 `json:"access_hash,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TelegramChannel.Query().
//		GroupBy(telegramchannel.FieldAccessHash).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tcq *TelegramChannelQuery) GroupBy(field string, fields ...string) *TelegramChannelGroupBy {
	tcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TelegramChannelGroupBy{build: tcq}
	grbuild.flds = &tcq.ctx.Fields
	grbuild.label = telegramchannel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AccessHash int64 `json:"access_hash,omitempty"`
//	}
//
//	client.TelegramChannel.Query().
//		Select(telegramchannel.FieldAccessHash).
//		Scan(ctx, &v)
func (tcq *TelegramChannelQuery) Select(fields ...string) *TelegramChannelSelect {
	tcq.ctx.Fields = append(tcq.ctx.Fields, fields...)
	sbuild := &TelegramChannelSelect{TelegramChannelQuery: tcq}
	sbuild.label = telegramchannel.Label
	sbuild.flds, sbuild.scan = &tcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TelegramChannelSelect configured with the given aggregations.
func (tcq *TelegramChannelQuery) Aggregate(fns ...AggregateFunc) *TelegramChannelSelect {
	return tcq.Select().Aggregate(fns...)
}

func (tcq *TelegramChannelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tcq); err != nil {
				return err
			}
		}
	}
	for _, f := range tcq.ctx.Fields {
		if !telegramchannel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tcq.path != nil {
		prev, err := tcq.path(ctx)
		if err != nil {
			return err
		}
		tcq.sql = prev
	}
	return nil
}

func (tcq *TelegramChannelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TelegramChannel, error) {
	var (
		nodes = []*TelegramChannel{}
		_spec = tcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TelegramChannel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TelegramChannel{config: tcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tcq *TelegramChannelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tcq.querySpec()
	_spec.Node.Columns = tcq.ctx.Fields
	if len(tcq.ctx.Fields) > 0 {
		_spec.Unique = tcq.ctx.Unique != nil && *tcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tcq.driver, _spec)
}

func (tcq *TelegramChannelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(telegramchannel.Table, telegramchannel.Columns, sqlgraph.NewFieldSpec(telegramchannel.FieldID, field.TypeInt64))
	_spec.From = tcq.sql
	if unique := tcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tcq.path != nil {
		_spec.Unique = true
	}
	if fields := tcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, telegramchannel.FieldID)
		for i := range fields {
			if fields[i] != telegramchannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tcq *TelegramChannelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tcq.driver.Dialect())
	t1 := builder.Table(telegramchannel.Table)
	columns := tcq.ctx.Fields
	if len(columns) == 0 {
		columns = telegramchannel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tcq.sql != nil {
		selector = tcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tcq.ctx.Unique != nil && *tcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tcq.predicates {
		p(selector)
	}
	for _, p := range tcq.order {
		p(selector)
	}
	if offset := tcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TelegramChannelGroupBy is the group-by builder for TelegramChannel entities.
type TelegramChannelGroupBy struct {
	selector
	build *TelegramChannelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tcgb *TelegramChannelGroupBy) Aggregate(fns ...AggregateFunc) *TelegramChannelGroupBy {
	tcgb.fns = append(tcgb.fns, fns...)
	return tcgb
}

// Scan applies the selector query and scans the result into the given value.
func (tcgb *TelegramChannelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tcgb.build.ctx, ent.OpQueryGroupBy)
	if err := tcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TelegramChannelQuery, *TelegramChannelGroupBy](ctx, tcgb.build, tcgb, tcgb.build.inters, v)
}

func (tcgb *TelegramChannelGroupBy) sqlScan(ctx context.Context, root *TelegramChannelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tcgb.fns))
	for _, fn := range tcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tcgb.flds)+len(tcgb.fns))
		for _, f := range *tcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TelegramChannelSelect is the builder for selecting fields of TelegramChannel entities.
type TelegramChannelSelect struct {
	*TelegramChannelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tcs *TelegramChannelSelect) Aggregate(fns ...AggregateFunc) *TelegramChannelSelect {
	tcs.fns = append(tcs.fns, fns...)
	return tcs
}

// Scan applies the selector query and scans the result into the given value.
func (tcs *TelegramChannelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tcs.ctx, ent.OpQuerySelect)
	if err := tcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TelegramChannelQuery, *TelegramChannelSelect](ctx, tcs.TelegramChannelQuery, tcs, tcs.inters, v)
}

func (tcs *TelegramChannelSelect) sqlScan(ctx context.Context, root *TelegramChannelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tcs.fns))
	for _, fn := range tcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
