// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TelegramChannel is the predicate function for telegramchannel builders.
type TelegramChannel func(*sql.Selector)

// TelegramSession is the predicate function for telegramsession builders.
type TelegramSession func(*sql.Selector)

// Try is the predicate function for try builders.
type Try func(*sql.Selector)
