// Code generated by ent, DO NOT EDIT.

package telegramchannel

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the telegramchannel type in the database.
	Label = "telegram_channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccessHash holds the string denoting the access_hash field in the database.
	FieldAccessHash = "access_hash"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// Table holds the table name of the telegramchannel in the database.
	Table = "telegram_channels"
)

// Columns holds all SQL columns for telegramchannel fields.
var Columns = []string{
	FieldID,
	FieldAccessHash,
	FieldTitle,
	FieldActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the TelegramChannel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccessHash orders the results by the access_hash field.
func ByAccessHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessHash, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}
