-- Modify "telegram_channels" table
ALTER TABLE "telegram_channels" DROP COLUMN "save_records", DROP COLUMN "save_favorite_records";
-- Create "last_tries" table
CREATE TABLE "last_tries" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "try" timestamptz NOT NULL, PRIMARY KEY ("id"));
