-- Create "tries" table
CREATE TABLE "tries" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "type" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "try_id_type" to table: "tries"
CREATE UNIQUE INDEX "try_id_type" ON "tries" ("id", "type");
-- Drop "last_tries" table
DROP TABLE "last_tries";
