-- Create "telegram_channels" table
CREATE TABLE "telegram_channels" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "access_hash" bigint NOT NULL, "title" character varying NOT NULL, "save_records" boolean NULL, "save_favorite_records" boolean NULL, "active" boolean NOT NULL, PRIMARY KEY ("id"));
-- Create "telegram_sessions" table
CREATE TABLE "telegram_sessions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "data" bytea NOT NULL, PRIMARY KEY ("id"));
