// Code generated by ogen, DO NOT EDIT.
package oas

type AccountV1GetActiveRegionRes interface {
	accountV1GetActiveRegionRes()
}

type AccountV1GetActiveShardRes interface {
	accountV1GetActiveShardRes()
}

type AccountV1GetByAccessTokenRes interface {
	accountV1GetByAccessTokenRes()
}

type AccountV1GetByPuuidRes interface {
	accountV1GetByPuuidRes()
}

type AccountV1GetByRiotIdRes interface {
	accountV1GetByRiotIdRes()
}

type ChampionMasteryV4GetAllChampionMasteriesByPUUIDRes interface {
	championMasteryV4GetAllChampionMasteriesByPUUIDRes()
}

type ChampionMasteryV4GetChampionMasteryByPUUIDRes interface {
	championMasteryV4GetChampionMasteryByPUUIDRes()
}

type ChampionMasteryV4GetChampionMasteryScoreByPUUIDRes interface {
	championMasteryV4GetChampionMasteryScoreByPUUIDRes()
}

type ChampionMasteryV4GetTopChampionMasteriesByPUUIDRes interface {
	championMasteryV4GetTopChampionMasteriesByPUUIDRes()
}

type ChampionV3GetChampionInfoRes interface {
	championV3GetChampionInfoRes()
}

type ClashV1GetPlayersByPUUIDRes interface {
	clashV1GetPlayersByPUUIDRes()
}

type ClashV1GetTeamByIdRes interface {
	clashV1GetTeamByIdRes()
}

type ClashV1GetTournamentByIdRes interface {
	clashV1GetTournamentByIdRes()
}

type ClashV1GetTournamentByTeamRes interface {
	clashV1GetTournamentByTeamRes()
}

type ClashV1GetTournamentsRes interface {
	clashV1GetTournamentsRes()
}

type LeagueExpV4GetLeagueEntriesRes interface {
	leagueExpV4GetLeagueEntriesRes()
}

type LeagueV4GetChallengerLeagueRes interface {
	leagueV4GetChallengerLeagueRes()
}

type LeagueV4GetGrandmasterLeagueRes interface {
	leagueV4GetGrandmasterLeagueRes()
}

type LeagueV4GetLeagueByIdRes interface {
	leagueV4GetLeagueByIdRes()
}

type LeagueV4GetLeagueEntriesByPUUIDRes interface {
	leagueV4GetLeagueEntriesByPUUIDRes()
}

type LeagueV4GetLeagueEntriesRes interface {
	leagueV4GetLeagueEntriesRes()
}

type LeagueV4GetMasterLeagueRes interface {
	leagueV4GetMasterLeagueRes()
}

type LolChallengesV1GetAllChallengeConfigsRes interface {
	lolChallengesV1GetAllChallengeConfigsRes()
}

type LolChallengesV1GetAllChallengePercentilesRes interface {
	lolChallengesV1GetAllChallengePercentilesRes()
}

type LolChallengesV1GetChallengeConfigsRes interface {
	lolChallengesV1GetChallengeConfigsRes()
}

type LolChallengesV1GetChallengeLeaderboardsRes interface {
	lolChallengesV1GetChallengeLeaderboardsRes()
}

type LolChallengesV1GetChallengePercentilesRes interface {
	lolChallengesV1GetChallengePercentilesRes()
}

type LolChallengesV1GetPlayerDataRes interface {
	lolChallengesV1GetPlayerDataRes()
}

type LolRsoMatchV1GetMatchIdsRes interface {
	lolRsoMatchV1GetMatchIdsRes()
}

type LolRsoMatchV1GetMatchRes interface {
	lolRsoMatchV1GetMatchRes()
}

type LolRsoMatchV1GetTimelineRes interface {
	lolRsoMatchV1GetTimelineRes()
}

type LolStatusV4GetPlatformDataRes interface {
	lolStatusV4GetPlatformDataRes()
}

type LorDeckV1CreateDeckRes interface {
	lorDeckV1CreateDeckRes()
}

type LorDeckV1GetDecksRes interface {
	lorDeckV1GetDecksRes()
}

type LorInventoryV1GetCardsRes interface {
	lorInventoryV1GetCardsRes()
}

type LorMatchV1GetMatchIdsByPUUIDRes interface {
	lorMatchV1GetMatchIdsByPUUIDRes()
}

type LorMatchV1GetMatchRes interface {
	lorMatchV1GetMatchRes()
}

type LorRankedV1GetLeaderboardsRes interface {
	lorRankedV1GetLeaderboardsRes()
}

type LorStatusV1GetPlatformDataRes interface {
	lorStatusV1GetPlatformDataRes()
}

type MatchV5GetMatchIdsByPUUIDRes interface {
	matchV5GetMatchIdsByPUUIDRes()
}

type MatchV5GetMatchRes interface {
	matchV5GetMatchRes()
}

type MatchV5GetTimelineRes interface {
	matchV5GetTimelineRes()
}

type SpectatorTftV5GetCurrentGameInfoByPuuidRes interface {
	spectatorTftV5GetCurrentGameInfoByPuuidRes()
}

type SpectatorTftV5GetFeaturedGamesRes interface {
	spectatorTftV5GetFeaturedGamesRes()
}

type SpectatorV5GetCurrentGameInfoByPuuidRes interface {
	spectatorV5GetCurrentGameInfoByPuuidRes()
}

type SpectatorV5GetFeaturedGamesRes interface {
	spectatorV5GetFeaturedGamesRes()
}

type SummonerV4GetByAccessTokenRes interface {
	summonerV4GetByAccessTokenRes()
}

type SummonerV4GetByPUUIDRes interface {
	summonerV4GetByPUUIDRes()
}

type TftLeagueV1GetChallengerLeagueRes interface {
	tftLeagueV1GetChallengerLeagueRes()
}

type TftLeagueV1GetGrandmasterLeagueRes interface {
	tftLeagueV1GetGrandmasterLeagueRes()
}

type TftLeagueV1GetLeagueByIdRes interface {
	tftLeagueV1GetLeagueByIdRes()
}

type TftLeagueV1GetLeagueEntriesByPUUIDRes interface {
	tftLeagueV1GetLeagueEntriesByPUUIDRes()
}

type TftLeagueV1GetLeagueEntriesRes interface {
	tftLeagueV1GetLeagueEntriesRes()
}

type TftLeagueV1GetMasterLeagueRes interface {
	tftLeagueV1GetMasterLeagueRes()
}

type TftLeagueV1GetTopRatedLadderRes interface {
	tftLeagueV1GetTopRatedLadderRes()
}

type TftMatchV1GetMatchIdsByPUUIDRes interface {
	tftMatchV1GetMatchIdsByPUUIDRes()
}

type TftMatchV1GetMatchRes interface {
	tftMatchV1GetMatchRes()
}

type TftStatusV1GetPlatformDataRes interface {
	tftStatusV1GetPlatformDataRes()
}

type TftSummonerV1GetByAccessTokenRes interface {
	tftSummonerV1GetByAccessTokenRes()
}

type TftSummonerV1GetByPUUIDRes interface {
	tftSummonerV1GetByPUUIDRes()
}

type TournamentStubV5CreateTournamentCodeRes interface {
	tournamentStubV5CreateTournamentCodeRes()
}

type TournamentStubV5GetLobbyEventsByCodeRes interface {
	tournamentStubV5GetLobbyEventsByCodeRes()
}

type TournamentStubV5GetTournamentCodeRes interface {
	tournamentStubV5GetTournamentCodeRes()
}

type TournamentStubV5RegisterProviderDataRes interface {
	tournamentStubV5RegisterProviderDataRes()
}

type TournamentStubV5RegisterTournamentRes interface {
	tournamentStubV5RegisterTournamentRes()
}

type TournamentV5CreateTournamentCodeRes interface {
	tournamentV5CreateTournamentCodeRes()
}

type TournamentV5GetGamesRes interface {
	tournamentV5GetGamesRes()
}

type TournamentV5GetLobbyEventsByCodeRes interface {
	tournamentV5GetLobbyEventsByCodeRes()
}

type TournamentV5GetTournamentCodeRes interface {
	tournamentV5GetTournamentCodeRes()
}

type TournamentV5RegisterProviderDataRes interface {
	tournamentV5RegisterProviderDataRes()
}

type TournamentV5RegisterTournamentRes interface {
	tournamentV5RegisterTournamentRes()
}

type TournamentV5UpdateCodeRes interface {
	tournamentV5UpdateCodeRes()
}

type ValConsoleMatchV1GetMatchRes interface {
	valConsoleMatchV1GetMatchRes()
}

type ValConsoleMatchV1GetMatchlistRes interface {
	valConsoleMatchV1GetMatchlistRes()
}

type ValConsoleMatchV1GetRecentRes interface {
	valConsoleMatchV1GetRecentRes()
}

type ValConsoleRankedV1GetLeaderboardRes interface {
	valConsoleRankedV1GetLeaderboardRes()
}

type ValContentV1GetContentRes interface {
	valContentV1GetContentRes()
}

type ValMatchV1GetMatchRes interface {
	valMatchV1GetMatchRes()
}

type ValMatchV1GetMatchlistRes interface {
	valMatchV1GetMatchlistRes()
}

type ValMatchV1GetRecentRes interface {
	valMatchV1GetRecentRes()
}

type ValRankedV1GetLeaderboardRes interface {
	valRankedV1GetLeaderboardRes()
}

type ValStatusV1GetPlatformDataRes interface {
	valStatusV1GetPlatformDataRes()
}
