// Code generated by ent, DO NOT EDIT.

package lasttry

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the lasttry type in the database.
	Label = "last_try"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTry holds the string denoting the try field in the database.
	FieldTry = "try"
	// Table holds the table name of the lasttry in the database.
	Table = "last_tries"
)

// Columns holds all SQL columns for lasttry fields.
var Columns = []string{
	FieldID,
	FieldTry,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the LastTry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTry orders the results by the try field.
func ByTry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTry, opts...).ToFunc()
}
